version: '3.5'

services:

  ingester:
    build:
      ./ingester
    container_name: data-ingester
    links:
      - kafka



  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka:9092, OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # Create a topic NAME:PARTITION:REPLICAS
      KAFKA_CREATE_TOPICS: "receivers:1:1, senders:1:1"
    ports:
      - 9094:9094
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9092"]
      interval: 15s
      timeout: 5s
      retries: 5
    links: 
      - zookeeper

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.3
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    links:
      - zookeeper
      - kafka


  eventstore-db:
    image: eventstore/eventstore:21.10.0-buster-slim
    container_name: eventstore-db
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    # volumes:
    #   - type: volume
    #     source: eventstore-volume-data
    #     target: /var/lib/eventstore
    #   - type: volume
    #     source: eventstore-volume-logs
    #     target: /var/log/eventstore


  eventstore-data-appender:
    image: eventstore-data-appender
    container_name: eventstore-data-appender
    links:
      - kafka
      - eventstore-db
      


  neo4j:
    image: docker.io/bitnami/neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    # volumes:
    #   - "neo4j_data:/bitnami"




  # solana_node:
  #   image: solanalabs/solana:v1.14.7
  #   container_name: solana_node
  #   ports:
  #     - "8899:8899"
  #     - "8900:8900"
  #   volumes:
  #       - ./solana_node/solana-run.sh:/usr/bin/solana-run.sh

    # healthcheck:
    #   test: [ "CMD", "solana-cli", "ping" ]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 30
    # restart: unless-stopped



# volumes:
#   eventstore-volume-data:
#   eventstore-volume-logs:











